apiVersion: v1
kind: Pod
metadata:
  name: nginx-cisco
  labels:
    app: nginx-dev
    version: v1
spec:
  volumes:
    - name: "data-cisco"
      hostPath:
        path: "/var/lib/cisco"
  containers:
    - image: nginx:latest
      name: nginx
      ports:
        - containerPort: 80
          name: nginx
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
      volumeMounts:
        - mountPath: "/data"
          name: "data-cisco"