apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-cisco
spec:
  replicas: 2
  selector:
    matchLabels: ##标签选择算符
      app: nginx-cisco
  template:
    metadata:
      labels:
        app: nginx-cisco
    spec:
      containers:
        - name: nginx-cisco
          image: nginx
          ports:
            - containerPort: 80