apiVersion: v1
kind: Pod
metadata:
  name: mysql-cisco
spec:
  volumes:
    - name: "data-cisco"
      hostPath:
        path: "/var/lib/cisco"
  containers:
    - image: mysql:latest
      name: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 3306
          name: mysql
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "2000m"
          memory: "2560Mi"
      volumeMounts:
        - mountPath: "/data"
          name: "data-cisco"