apiVersion: v1
kind: Pod
metadata: #资源的元数据/属性
  name: test-pod #资源的名字，在同一个namespace中必须唯一
  labels: #设定资源的标签
    k8s-app: apache
    version: v1
    kubernetes.io/cluster-service: "true"
  annotations: #自定义注解列表
    - name: String        #自定义注解名字
spec:
  volumes:
    - name: "kuard-data"
      # 使用卷(或者使用下面远程网络存储卷，适用于云环境，只需要选择一种)
      hostPath: #挂在主机文件系统
        path: "/var/lib/kuard"
      #nfs: # 挂载远程网络存储卷
      #  server: my.nfs.server.local
      #  path: "/exports"
  containers:
    - image: grc.io/kuard-demo/kuard-amd64:blue
      name: kuard
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "1000m"
          memory: "256Mi"
      volumeMounts:
        - mountPath: "/data"
          name: "kuard-data"
      livenessProbe: # 存活探针
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe: # 就绪探针
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 30
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
